### ISSUE TITLE
default_user check fails when image has no tags

### ISSUE THREAD

**Issue by bahamat** [joyent/triton-ansible-inventory#1]
```
$ ./inventory/triton-ansible-inventory --list                                                                                         
/Users/bahamat/repos/joyent/Joyent_Dev-ansible/node_modules/triton-ansible-inventory/bin/triton-ansible-inventory.js:153
                                if (Object.prototype.hasOwnProperty.call(image.tags, 'default_user')) {
                                                                    ^

TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at /Users/bahamat/repos/joyent/Joyent_Dev-ansible/node_modules/triton-ansible-inventory/bin/triton-ansible-inventory.js:153:69
    at done (/Users/bahamat/repos/joyent/Joyent_Dev-ansible/node_modules/triton/lib/tritonapi.js:754:17)
    at next (/Users/bahamat/repos/joyent/Joyent_Dev-ansible/node_modules/triton/node_modules/vasync/lib/vasync.js:201:4)
    at Object.cloudApiGetImage [as func] (/Users/bahamat/repos/joyent/Joyent_Dev-ansible/node_modules/triton/lib/tritonapi.js:738:21)
    at Immediate.<anonymous> (/Users/bahamat/repos/joyent/Joyent_Dev-ansible/node_modules/triton/node_modules/vasync/lib/vasync.js:213:20)
    at processImmediate (internal/timers.js:464:21)
```

**Comment by bahamat** [comment]
Fixed in 306ff950688a9af53dfa76a117c4c8f1f040d973.
